language: android
sudo: false
jdk: oraclejdk7
env:
  global:
  - GRADLE_OPTS="-Xmx2048M -XX:MaxPermSize=2048M"
  matrix:
  - ADB_INSTALL_TIMEOUT=15 ANDROID_BUILD_TOOLS_VERSION=23.0.3 ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
android:
  components:
# first 'tools' updates SDK tools 'til last version ** in remote repository number 10 **
  - tools
# second 'tools' updates SDK tools 'til last version ** in remote repository number 11 ** (current last one)
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-23
before_install:
  - ci/decrypt_files
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 20M
  - emulator -avd test -no-skin -no-audio -no-window &
  - chmod +x ./ci/wait_for_emulator.sh
  - ./ci/wait_for_emulator.sh
script:
# build app and assemble APK, in debug mode
  - ./gradlew clean assemble test -Dpre-dex=false --stacktrace
after_success:
  - bash < ci/codecov
  - ci/deploy_all
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: 'app/build/outputs/apk/app-prod-release.apk'
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    all_branches: true
