#!/bin/bash

DIR=$(dirname $0)

sudo apt-get install python-openssl
sudo pip install google-api-python-client

python $DIR/basic_upload_apks.py com.athelite $DIR/../app/build/outputs/apk/app-production-release.apk